image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

stages:
  - build
  - deploy

build-and-push:
  stage: build
  script:
    - docker build -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:latest"
    - docker logout

deploy-to-render:
  stage: deploy
  script:
    - apk add --no-cache curl
    - curl -X POST "$RENDER_DEPLOY_HOOK"