version: '3.9'
services:
  app:
    build: .
    container_name: projeto_de_merda_n2_app
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: streamlit run src/app.py
    environment:
      - PYTHONUNBUFFERED=1
